### ISSUE TITLE
Bugs in the calculation of integrated gradient

### ISSUE THREAD

**Issue by VicaYang** [TianhongDai/integrated-gradient-pytorch#3]
The sum of the integrated gradients should be the change of the prediction score (F(x)-F(x')), which is also **Proposition 1** in the paper. However, the integrated gradients calculated in this repo is wrong so that this proposition is not hold.
After checking the code and comparing it with the code provided by the authors, I found that you used the wrong (x-x') in the calculation, which should be the inputs that are calculating gradients.
I make a pull request to tackle this issue.

**Comment by TianhongDai** [comment]
@VicaYang Thanks for finding the bug and tackle this issue.
